controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    gunnerycar_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true

    gunnerycar_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    gunnerycar_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

gunnerycar_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

gunnerycar_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.20
    wheel_radius: 0.032

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.00, 0.00, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.00, 0.0, 0.0, 0.0, 0.0, 0.0]
    
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    use_sim_time: true