<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
    <xacro:include filename="$(find gunnerycar)/urdf/common_inertial.xacro"/>
    <xacro:macro name="base_link" params="length radius">
        <!--机器人身体部分-->
        <link name="base_link">
            <!--外观描述-->
            <visual>
                <!--偏移和旋转-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!--几何形状-->
                <geometry>
                    <!--圆柱体, 单位m-->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!--材质-->
                <material name="white">
                    <!--颜色RGBA格式-->
                    <color rgba="1 1 1 0.5"/>
                </material>
            </visual>

            <collision>
                <!--偏移和旋转-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!--几何形状-->
                <geometry>
                    <!--圆柱体, 单位m-->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!--材质-->
                <material name="white">
                    <!--颜色RGBA格式-->
                    <color rgba="1 1 1 0.5"/>
                </material>
            </collision>

            <!--惯性属性-->
            <xacro:cylinder_inertial m="1.0" r="${radius}" h="${length}"/>
        </link>

        <link name="base_footprint" />

        <joint name="base_joint" type="fixed">
            <!--父链接-->
            <parent link="base_footprint"/>
            <!--子链接-->
            <child link="base_link"/>
            <!--偏移和旋转-->
            <origin xyz="0.0 0.0 ${length / 2.0 + 0.032 - 0.001}" rpy="0.0 0.0 0.0"/>
        </joint>
    </xacro:macro>
</robot>