<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
    <xacro:include filename="$(find ackermann)/urdf/common_inertial.xacro"/>
    <xacro:macro name="base_link" params="length width height wheel_radius">
        <!--机器人身体部分-->
        <link name="base_link">
            <!--外观描述-->
            <visual>
                <!--偏移和旋转-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!--几何形状-->
                <geometry>
                    <!--长方体, 单位m-->
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <!--材质-->
                <material name="white">
                    <!--颜色RGBA格式-->
                    <color rgba="1 1 1 0.5"/>
                </material>
            </visual>

            <collision>
                <!--偏移和旋转-->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!--几何形状-->
                <geometry>
                    <!--长方体, 单位m-->
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <!--材质-->
                <material name="white">
                    <!--颜色RGBA格式-->
                    <color rgba="1 1 1 0.5"/>
                </material>
            </collision>

            <!--惯性属性-->
            <xacro:box_inertial m="25.0" w="${width}" d="${length}" h="${height}"/>
        </link>

        <link name="base_footprint" />

        <joint name="base_joint" type="fixed">
            <!--父链接-->
            <parent link="base_footprint"/>
            <!--子链接-->
            <child link="base_link"/>
            <!--偏移和旋转-->
            <origin xyz="0.0 0.0 ${height / 2.0 + wheel_radius - 0.001}" rpy="0.0 0.0 0.0"/>
        </joint>

        <link name="virtual_steer_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <box size="0.01 0.15 0.01" />
                </geometry>
                <material name="">
                    <color rgba="1.0 1.0 0.0 1" />
                </material>
            </visual>
            <inertial>  <!-- Gazebo won't show this link without this inertial mass -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.001" />
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
            </inertial>
        </link>
        <joint name="virtual_steering_wheel_joint" type="revolute">
            <origin xyz="0.12 0.0 0.0" rpy="0.0 0.0 0.0" />
            <parent link="base_link" />
            <child link="virtual_steer_link" />
            <axis xyz="-1 0 0" />
            <limit lower="-3.14159" upper="3.14159" effort="200" velocity="20" />
        </joint>

        <gazebo reference="virtual_steer_link">
            <material>Gazebo/Yellow</material>
        </gazebo>

    </xacro:macro>
</robot>