/autofleet_node:
  ros__parameters:
    target_pose:
    - 17.5
    - 4.0
    - 0.0
    - 0.0
    - 0.0
    - 1.57
    use_sim_time: false
    plugins:
    - "FormTeamState"
    - "MoveState"
    - "BreakTeamState"
    robots_name: ["robot1"]
    robot1: [0.0 ,0.0]
