/robot1/init_pose_node:
  ros__parameters:
    init_pose:
    - 0.01
    - 0.01
    - 0.01
    - 0.0
    - 0.0
    - 0.0
    use_sim_time: false

/robot1/init_target_node:
  ros__parameters:
    init_target_pose:
    - 17.5
    - 4.0
    - 0.0
    - 0.0
    - 0.0
    - 1.57
    use_sim_time: false

/robot2/init_pose_node:
  ros__parameters:
    init_pose:
    - 0.0
    - 0.0
    - 0.1
    - 0.0
    - 0.0
    - 0.0
    use_sim_time: false
